### PR TITLE
Add Furtherance

### PR DESCRIPTION
**Pull request by rickykresslein**
changelog: Added Furtherance as an alternative to Toggl Track in the Utilities section.

### CODE REVIEW

**Comment by azzamsa** [comment]
Never know this app exists. I have been searching for a time tracker app. But this app never shows up in search engines result.

**Comment by rickykresslein** [comment]
@azzamsa I hope you like it! Hopefully adding it to this list helps other people to find it too!

**Review by TaKO8Ki — APPROVED** [review]
Thanks!

**Comment by TaKO8Ki** [comment]
The errors that happened on CI are not related to this pull request.

**Pull request merged**
