### PR TITLE
Add `pls` and drop `exa`

### PR DESCRIPTION
**Pull request by dhruvkb**
*Please write a short comment explaining your change (or "none" for internal only changes)*

changelog: Adds `pls`, a new `ls` alternative, and drops `exa` as it has been deprecated.

### CODE REVIEW

**Comment by d3-X-t3r** [comment]
`pls` isn't quite the same as `exa` and isn't really a replacement for it.
`exa`'s "official" replacement is `eza`, which is actively being maintained: https://github.com/eza-community/eza , therefore it should be replaced with `eza`.

**Comment by dhruvkb** [comment]
Oh I'm sorry I didn't mean `pls` as a substitute for `exa` but rather as two separate unrelated actions (adding one `ls` alternative, and removing a deprecated one). `eza` should also be included in the list for sure!

**Comment by halostatue** [comment]
I think that the suggestion is to replace `exa` with `eza` while adding `pls`.

**Comment by dhruvkb** [comment]
Updated to include `eza` as well 👍.

**Comment by dhruvkb** [comment]
This repo seems unmaintained, so I'm going to close this PR now.

**Pull request closed without merging**
